# Generated by Django 3.2.5 on 2021-08-19 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rivername', models.CharField(max_length=300)),
                ('fishname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rn', models.CharField(max_length=500)),
                ('fn', models.CharField(max_length=500)),
                ('water', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishapp.river')),
            ],
        ),
    ]
